services:
    app:
        container_name: exa_app
        image: %%IMAGE%%
        tty: true
        ports:
            - "8118:8118"
        volumes:
            - .:/opt/src
        working_dir: /opt/src
        command: %%COMMAND%%
        env_file:
            - .env
    console:
        container_name: exa_console
        image: %%IMAGE%%
        tty: true
        init: true
        volumes:
            - .:/opt/src
        working_dir: /opt/src
        env_file:
            - .env
        profiles:
            - nostart
