services:
    app:
        container_name: exa_app
        image: node:20
        tty: true
        ports:
            - "8118:8118"
        volumes:
            - .:/opt/src
        working_dir: /opt/src
        command: bash -c 'npm i; npx --yes jmig migrate; npm start'
        env_file:
            - .env
    console:
        container_name: exa_console
        image: node:20
        tty: true
        init: true
        volumes:
            - .:/opt/src
        working_dir: /opt/src
        env_file:
            - .env
        profiles:
            - nostart
