name: Deploy Docusaurus Documentation

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

defaults:
 run:
  working-directory: ./docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  # Use Node.js 18 here

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
